name: Test

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ startsWith(github.ref, 'refs/pull/') || github.run_number }}  # yamllint disable-line
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0
        with:
          python-version: '3.10'
          activate-environment: true

      - name: Install package
        run: |
          # `-e` for coverage report.
          uv pip install --torch-backend=cpu -e '.[test]'

      - name: Run tests
        run: |
          pytest --cov=sdm --cov-config=pyproject.toml --cov-report=term-missing

      # TODO: Uncomment when we make the repo public.
      # - name: Upload coverage
      #   if: ${{ runner.os == 'Linux' }}
      #   uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
      #   with:
      #     fail_ci_if_error: false
