name: Test

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ startsWith(github.ref, 'refs/pull/') || github.run_number }}  # yamllint disable-line
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

permissions:
  contents: read
  pull-requests: write

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0
        with:
          python-version: '3.10'
          activate-environment: true

      - name: Install package
        run: |
          uv pip install --torch-backend=cpu -e '.[test]'

      - name: Get branch name or PR number
        id: branch_or_pr
        run: |
          echo "ref=${{ github.event_name == 'push' && github.ref_name || github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"

      - name: Run tests
        run: |
          pytest --cov=sdm --cov-config=pyproject.toml --cov-report=xml:coverage.xml --cov-report=html:htmlcov

      - name: Upload coverage report
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v7
        with:
          name: structured-data-models-coverage-${{ steps.branch_or_pr.outputs.ref }}
          path: |
            coverage.xml
            htmlcov/
          retention-days: 7

      - name: Summarize code coverage
        if: always()
        continue-on-error: true
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage.xml'
          badge: true
          thresholds: '80 90'
          format: 'markdown'
          output: both
          hide_complexity: true

      - name: Print coverage in job summary
        if: always()
        continue-on-error: true
        run: |
          {
            echo "* [Coverage artifact](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
            echo
            echo "<details><summary>View coverage summary table</summary>"
            echo
            if [[ -f code-coverage-results.md ]]; then
              cat code-coverage-results.md
            else
              echo "Coverage summary was not generated."
            fi
            echo
            echo "</details>"
          } > coverage-comment.md
          cat coverage-comment.md >> "$GITHUB_STEP_SUMMARY"
          mv coverage-comment.md code-coverage-results.md

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        continue-on-error: true
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0  # v3.0.4
        with:
          recreate: true
          path: code-coverage-results.md
